added Get signed TX
questbook/zero-wallet-client-sdk pull request #2
Opened 2022-10-07 14:30 UTC by alimansour0002

2022-10-07 19:55 UTC, hasankhadra requested changes

2022-10-07 19:55 UTC, hasankhadra commented on packages/my-react-package/src/MetaWallet.tsx
> +    async getSignedTX(scwAddress: string, chainId: string, safeTxBody: BuildExecTransaction):Promise<string>{
Let's put the `scwAddress` as an attribute of the MetaWallet class instead of passing it as a parameter.

2022-10-07 23:04 UTC, hasankhadra requested changes

2022-10-07 23:04 UTC, hasankhadra commented on packages/my-react-package/src/MetaWallet.tsx
> +            verifyingContract: this.address,
this.address should be the address of the MetaWallet. 
The MetaWallet and the SCW have different addresses. You can add another attribute called this.scwAddress

2022-10-07 23:48 UTC, closed without merging

2022-10-08 04:53 UTC, madhavanmalolan reviewed
Why is this package called my react package

2022-10-08 04:53 UTC, madhavanmalolan commented on packages/my-react-package/src/MetaWallet.tsx
> +        console.log('ww', localStorage.getItem('webwalletPrivateKey'));
Can we please use a logger

2022-10-08 04:53 UTC, madhavanmalolan commented on packages/my-react-package/src/MetaContract.tsx
> +    private supportedChains =
Why is this not importing from constants/supportedchains